apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: crossplane-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args: ["server", "/data", "--console-address", ":9001"]
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: crossplane-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: minio
  ports:
    - name: server
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: console
      port: 9001
      targetPort: 9001
      protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: crossplane-system
stringData:
  credentials: |-
    {
      "user": "minioadmin",
      "password": "minioadmin"
    }
