apiVersion: minio.crossplane.io/v1alpha1
kind: AccessKey
metadata:
  annotations:
    meta.upbound.io/example-id: minio/v1alpha1/accesskey
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    userSelector:
      matchLabels:
        testing.upbound.io/example-name: example_user

---

apiVersion: iam.minio.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: /v1alpha1/accesskey
  labels:
    testing.upbound.io/example-name: example_user
  name: example-user
spec:
  forProvider: {}
