apiVersion: iam.minio.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/serviceaccount
  labels:
    testing.upbound.io/example-name: test_service_account
  name: test-service-account
spec:
  forProvider:
    targetUserSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: iam.minio.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/serviceaccount
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    forceDestroy: true
    tags:
      tag-key: tag-value
